export const ErrorMessages = {
  IS_EMPTY: '$property should not be empty',
  NOT_FOUND: '$property is not found',
  EXISTS: '$property already exists',
  SOMETHING_WENT_WRONG: 'Something went wrong with $property',
  IS_NOT_VALID: '$property should be valid',
  IS_NOT_STRING: '$property should be string',
  IS_NOT_DATE: '$property should be a date value',
  IS_NOT_NUMBER: '$property should be a number',
  IS_NOT_BOOLEAN: '$property should have a boolean value',
  IS_NOT_ARRAY: '$property should be an array',
  MIN: '$property should at least be $constraint1',
  MAX: '$property should at most be $constraint1',
  DATABASE_CONNECTION_ERROR: 'Database connection error',
  PASSWORD_STRENGTH_FAILED: 'Password strength failed',
  MISMATCH: '$property mismatch',
  EXPIRED: '$property has expired',
  REQUESTED: '$property has already been requested',
  FAILED_TO_CREATE: 'Failed to create $property',
  FAILED_TO_FETCH: 'Failed to fetch $property',
  FAILED_TO_ADD: 'Failed to add $property',
  FAILED_TO_UPDATE: 'Failed to update $property',
  FAILED_TO_DELETE: 'Failed to delete $property',
  FAILED_TO_SEND: 'Failed to send $property',
  LETTERS_ONLY: '$property should only contain letters',
  NOT_INCLUDED: '$property is not included',
  IS_EMPTY_STRING: '$property should not be an empty string',
  IS_NEGATIVE: '$property should not be negative',
  NOT_ACTIVE: '$property is not active',
  NOT_OPEN: '$property is not open',
};
