export const SuccessMessages = {
  CREATED_SUCCESSFULLY: 'success.CREATED_SUCCESSFULLY',
  UPDATED_SUCCESSFULLY: 'success.UPDATED_SUCCESSFULLY',
  DELETED_SUCCESSFULLY: 'success.DELETED_SUCCESSFULLY',
  ASSIGNED_SUCCESSFULLY: 'success.ASSIGNED_SUCCESSFULLY',
  TRUE: 'success.TRUE',
  FALSE: 'success.FALSE',
  REVOKED_SUCCESSFULLY: 'success.REVOKED_SUCCESSFULLY',
  OK: 'success.OK',
  SUCCESS: 'success.SUCCESS',
};
